spring.application.name=marketplace
management.endpoint.health.show-details=always
spring.docker.compose.lifecycle-management=start-only

# Regitration (MYSQL 3307)
registration.datasource.url=jdbc:mysql://localhost:3307/registration
registration.datasource.username=root
registration.datasource.password=123456
registration.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
registration.jpa.properties.hibernate.hbm2ddl.auto=update


#Catalog (MYSQL 3308)
catalog.datasource.url=jdbc:mysql://localhost:3308/catalog
catalog.datasource.username=root
catalog.datasource.password=123456
catalog.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
catalog.jpa.properties.hibernate.hbm2ddl.auto=create
